### ISSUE TITLE
NPE using Publish Review from commit in git log

### ISSUE THREAD

**Issue by a0shvedov** [ritesh-kapoor/review-board-idea-plugin#10]
null
java.lang.NullPointerException
    at com.intellij.ui.EditorTextFieldProviderImpl$MyEditorTextField.c(EditorTextFieldProviderImpl.java:68)
    at com.intellij.ui.EditorTextFieldProviderImpl$MyEditorTextField.createEditor(EditorTextFieldProviderImpl.java:56)
    at com.intellij.ui.EditorTextField.b(EditorTextField.java:367)
    at com.intellij.ui.EditorTextField.addNotify(EditorTextField.java:352)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at java.awt.Container.addNotify(Container.java:2773)
    at javax.swing.JComponent.addNotify(JComponent.java:4740)
    at javax.swing.JRootPane.addNotify(JRootPane.java:757)
    at java.awt.Container.addNotify(Container.java:2773)
    at java.awt.Window.addNotify(Window.java:770)
    at java.awt.Dialog.addNotify(Dialog.java:760)
    at java.awt.Window.pack(Window.java:807)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:677)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
    at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1637)
    at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1586)
    at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1601)
    at com.ritesh.idea.plugin.ui.action.ShowReviewBoard.showCreateReviewPanel(ShowReviewBoard.java:93)
    at com.ritesh.idea.plugin.ui.action.ShowReviewBoard.access$000(ShowReviewBoard.java:45)
    at com.ritesh.idea.plugin.ui.action.ShowReviewBoard$2$1.run(ShowReviewBoard.java:75)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by a0shvedov** [comment]
I installed the plugin from the ideaj's plugin repository,which is of version 0.1.1, my ideaj's version 15.0.1 Ultimate. Review Board 2.0.20

**Comment by ritesh-kapoor** [comment]
Could you please elaborate on how to recreate this bug. It would be very helpful.

**Comment by ritesh-kapoor** [comment]
Closing this issue. Please refer : #9
