### ISSUE TITLE
Does not work under 15.0.2 CE and 15 Ultimate

### ISSUE THREAD

**Issue by ariel777** [ritesh-kapoor/review-board-idea-plugin#13]
First of all thank you for working on it! I was looking forward to this plugin!
#15.0.2 CE

Unfortunately it does not work under 15.0.2 CE:

```
IntelliJ IDEA 15.0.2
Build #IC-143.1184, built on December 7, 2015
JRE: 1.8.0_51-b16 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation
```

Shows: "Unsupported VCS" in popup notification window while I have subversion setup (no dialog is shown).

In event log:

```
15:31:49 Unsupported VCS: Plugin doesnot supports current VCS
15:32:33 Unsupported VCS: Plugin doesnot supports current VCS
```
#15 Ultimate:

```
IntelliJ IDEA (Minerva) IU-143.1183.10
Build #IU-143.1183, built on December 2, 2015
JRE: 1.8.0_51-b16 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation
```

Displays dialog "Create Review Request"

But after clicking OK - "The file was not found in the repository":

In event log:

```
15:34:46 ReviewBoard Server: Server : The file was not found in the repository
```
# Extra logs

Nothing special in idea.log (let me know if other logs required)
## 15 Ultimate:

```
2015-12-16 15:12:08,681 [12055626]   INFO - lij.tasks.impl.TaskManagerImpl - Updating issues cache (every 20 min) 
2015-12-16 15:32:08,625 [13255570]   INFO - lij.tasks.impl.TaskManagerImpl - Updating issues cache (every 20 min) 
2015-12-16 15:33:24,260 [13331205]   INFO - ea.plugin.diff.SvnDiffProvider - Executing svn command : Parameters : [-r, HEAD] ,target :D:\sbdata\root\workspace\testbox\intellij-prjs@UNDEFINED
2015-12-16 15:34:46,485 [13413430]   WARN - dea.plugin.ui.ExceptionHandler - Server : The file was not found in the repository
```
## 15 CE

```
2015-12-16 14:16:33,697 [8867761]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 15.0.2  Build #IC-143.1184.17 
2015-12-16 14:16:33,697 [8867761]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_51 
2015-12-16 14:16:33,697 [8867761]  ERROR - plication.impl.ApplicationImpl - VM: Java HotSpot(TM) Server VM 
2015-12-16 14:16:33,698 [8867762]  ERROR - plication.impl.ApplicationImpl - Vendor: Oracle Corporation 
2015-12-16 14:16:33,698 [8867762]  ERROR - plication.impl.ApplicationImpl - OS: Windows 7 
2015-12-16 14:16:33,698 [8867762]  ERROR - plication.impl.ApplicationImpl - Last Action: ShowSettings 
2015-12-16 14:18:49,274 [9003338]   INFO - ackerWithProcessCanceledReport - ProcessCancelException was thrown while analyzing libraries. Cache has to be rebuilt. 
2015-12-16 14:18:49,275 [9003339]   INFO - ackerWithProcessCanceledReport - ProcessCancelException was thrown while analyzing libraries. Cache has to be rebuilt. 
2015-12-16 14:19:04,755 [9018819]   INFO - agnostic.FrequentEventDetector - Too many events posted, #1 
2015-12-16 14:19:04,844 [9018908]   INFO - agnostic.FrequentEventDetector - Too many events posted, #1 
2015-12-16 14:19:24,288 [9038352]   INFO - agnostic.FrequentEventDetector - Too many events posted, #2
java.lang.Throwable
    at com.intellij.openapi.diagnostic.FrequentEventDetector.eventHappened(FrequentEventDetector.java:70)
    at com.intellij.ide.IdeEventQueue.postEvent(IdeEventQueue.java:1164)
    at javax.swing.RepaintManager.scheduleProcessingRunnable(RepaintManager.java:1437)
    at javax.swing.RepaintManager.addDirtyRegion0(RepaintManager.java:459)
    at javax.swing.RepaintManager.addDirtyRegion(RepaintManager.java:481)
    at com.intellij.ide.IdeRepaintManager.addDirtyRegion(IdeRepaintManager.java:99)
    at javax.swing.JComponent.repaint(JComponent.java:4802)
    at java.awt.Component.repaint(Component.java:3346)
    at com.intellij.openapi.editor.impl.EditorComponentImpl.repaintEditorComponent(EditorComponentImpl.java:197)
    at com.intellij.openapi.editor.impl.EditorImpl.repaintLines(EditorImpl.java:1847)
    at com.intellij.openapi.editor.impl.EditorImpl.access$1000(EditorImpl.java:125)
    at com.intellij.openapi.editor.impl.EditorImpl$1.attributesChanged(EditorImpl.java:406)
    at com.intellij.openapi.editor.impl.EditorImpl$1.beforeRemoved(EditorImpl.java:374)
    at com.intellij.openapi.editor.impl.MarkupModelImpl.fireBeforeRemoved(MarkupModelImpl.java:244)
    at com.intellij.openapi.editor.impl.RangeHighlighterTree.fireBeforeRemoved(RangeHighlighterTree.java:76)
    at com.intellij.openapi.editor.impl.RangeHighlighterTree.fireBeforeRemoved(RangeHighlighterTree.java:27)
    at com.intellij.openapi.editor.impl.IntervalTreeImpl.beforeRemove(IntervalTreeImpl.java:1346)
    at com.intellij.openapi.editor.impl.IntervalTreeImpl.removeInterval(IntervalTreeImpl.java:980)
    at com.intellij.openapi.editor.impl.MarkupModelImpl.removeHighlighter(MarkupModelImpl.java:184)
    at com.intellij.openapi.editor.impl.RangeHighlighterImpl.unregisterInTree(RangeHighlighterImpl.java:352)
    at com.intellij.openapi.editor.impl.RangeMarkerImpl.dispose(RangeMarkerImpl.java:80)
    at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl$3.process(HighlightingSessionImpl.java:141)
    at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl$3.process(HighlightingSessionImpl.java:138)
    at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
    at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
    at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

2015-12-16 14:23:21,618 [9275682]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: editor for id: editor.preferences.import 
2015-12-16 14:23:36,282 [9290346]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: editor for id: editor.preferences.import 
2015-12-16 14:23:46,584 [9300648]   INFO - delayedCommit.RemoteRunSession - Personal session started: 382 Regression Failure: NPE's in ws_vm (WsImportTemplateTest, etc.) // http://ovmjira.us.oracle.com/browse/OVMQE-1371 
2015-12-16 14:23:51,994 [9306058]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: editor for id: editor.preferences.import 
2015-12-16 14:28:56,141 [9610205]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: editor for id: editor.preferences.import 
2015-12-16 14:29:26,215 [9640279]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: editor for id: editor.preferences.import 
2015-12-16 14:29:41,357 [9655421]   INFO - lij.tasks.impl.TaskManagerImpl - Updating issues cache (every 20 min) 
2015-12-16 14:36:24,569 [10058633]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: editor for id: editor.preferences.import 
2015-12-16 14:42:22,208 [10416272]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: editor for id: editor.preferences.import 
2015-12-16 14:49:41,420 [10855484]   INFO - lij.tasks.impl.TaskManagerImpl - Updating issues cache (every 20 min) 
2015-12-16 15:09:41,401 [12055465]   INFO - lij.tasks.impl.TaskManagerImpl - Updating issues cache (every 20 min) 
2015-12-16 15:29:41,344 [13255408]   INFO - lij.tasks.impl.TaskManagerImpl - Updating issues cache (every 20 min) 
```

**Comment by ritesh-kapoor** [comment]
Are you able to publish same review using RBTools?

**Comment by ariel777** [comment]
Honestly I do/did not use RBTools, I created a script to create patches via
svn (as Intellij Idea patches were not recognised by review board) and
integrated executing the script by Intellij by shortcut.

**Comment by ritesh-kapoor** [comment]
Plugin internally uses svn diff to publish to server. Were you able to publish your changes your script? and if possible can you try solution provided in #14

**Comment by ariel777** [comment]
Hi Ritesh,

Thank you for coming back.

> Plugin internally uses svn diff to publish to server. Were you able to
> publish your changes your script?
> Yes, I can. I use svn in script as well:

# output (diff-2-file-in-diff-dir.bat in att.):

D:\sbdata\Dev\MyScripts\diff-2-file-in-diff-dir.bat
intellij-prjs\testbox.ipr testbox xxxxx-main_ea_prj-testbox_a.diff
D:\sbdata\root\workspace\testbox

D:\sbdata\root\workspace\testbox>cd D:\sbdata\root\workspace\testbox

D:\sbdata\root\workspace\testbox>svn diff --patch-compatible
intellij-prjs\testbox.ipr
 1>>D:\sbdata\root\workspace\diffs\testbox\2015-12-22_xxxxx-main_ea_prj-testbox_a.diff

   Module Name:  testbox
   Orig File:    intellij-prjs\testbox.ipr
   Working Dir:  D:\sbdata\root\workspace\testbox

   Diff file:
 D:\sbdata\root\workspace\diffs\testbox\2015-12-22_xxxxx-main_ea_prj-testbox_a.diff
--- ALREADY IN CLIPBOARD [CREATED]  ! :)

# Process finished with exit code 0

> ...and if possible can you try solution provided in #14
> https://github.com/ritesh-kapoor/review-board-idea-plugin/issues/14
> Installed the plugin.

After clicking on "Publish review" in Version Control tab:

# Under 15 CE:

_Unsupported VCS_

# Plugin doesnot supports current VCS

# Under 15.0.3:

11:09:13 ReviewBoard Server: Server : The file was not found in the

# repository

Completely forgot to say: we have Review Board 1.7.28.

Thank you.

Have a nice day,
Alex

**Comment by ritesh-kapoor** [comment]
I would add "--patch-compatible" additional parameter while creating diff in svn
