### ISSUE TITLE
Incorrect path for diff is generated

### ISSUE THREAD

**Issue by vkaverin** [ritesh-kapoor/review-board-idea-plugin#35]
When trying to open diff from any review, get following exception:

```
Illegal char <:> at index 5: https://<here is svn repository URL>/somehting/Something.java
java.nio.file.InvalidPathException: Illegal char <:> at index 5: https://<here is svn repository URL>/somehting/Something.java
    at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
    at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
    at java.nio.file.Paths.get(Paths.java:84)
    at com.ritesh.idea.plugin.reviewboard.ReviewDataProvider$1.run(ReviewDataProvider.java:225)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

In UI it shows path of diff like

```
C:\Program Files\Java\jdk1.8.0_65\jre\bin\https://<here is svn repository URL>/somehting/Something.java
```

The problem has occured on Intellij Idea version 2016.1.
Reviewboard version is 2.5.1.1.

**Comment by AlexanderFinch** [comment]
I am also getting this error with a slightly different path:

```
Illegal char <:> at index 3: svn://username@<IP_ADDRESS>/var/svn/dev/sandbox/somefolder/Some File.java
java.nio.file.InvalidPathException: Illegal char <:> at index 3: svn://username@<IP_ADDRESS>/var/svn/dev/sandbox/somefolder/Some File.java
    at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
    at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
    at java.nio.file.Paths.get(Paths.java:84)
    at com.ritesh.idea.plugin.reviewboard.ReviewDataProvider$1.run(ReviewDataProvider.java:225)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

I have noticed that the particular file in my case has spaces in the name... might be a factor (updated this comment to reflect)

**Comment by AlexanderFinch** [comment]
I have figured out a workaround. When creating a review, it asks for a path. I have been putting in the svn location:
`svn://username@<IP_ADDRESS>/var/svn/dev/sandbox`
If I just use / (slash) the files can be viewed as diffs in the plugin.
