### ISSUE TITLE
Can't run in 2017.1 EAP

### ISSUE THREAD

**Issue by anshnd** [ritesh-kapoor/review-board-idea-plugin#45]
Updated to latest 0.1.3 allowing me to specify rbt's location.  Now I get:

`null
java.lang.NullPointerException
	at com.intellij.ui.EditorTextFieldProviderImpl$MyEditorTextField.d(EditorTextFieldProviderImpl.java:68)
	at com.intellij.ui.EditorTextFieldProviderImpl$MyEditorTextField.createEditor(EditorTextFieldProviderImpl.java:56)
	at com.intellij.ui.EditorTextField.a(EditorTextField.java:363)
	at com.intellij.ui.EditorTextField.addNotify(EditorTextField.java:348)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at javax.swing.JRootPane.addNotify(JRootPane.java:757)
	at java.awt.Container.addNotify(Container.java:2773)
	at java.awt.Window.addNotify(Window.java:770)
	at java.awt.Dialog.addNotify(Dialog.java:760)
	at java.awt.Window.pack(Window.java:807)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:669)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:457)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1688)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1637)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1652)
	at com.ritesh.idea.plugin.ui.action.ShowReviewBoard.showCreateReviewPanel(ShowReviewBoard.java:99)
	at com.ritesh.idea.plugin.ui.action.ShowReviewBoard.access$000(ShowReviewBoard.java:45)
	at com.ritesh.idea.plugin.ui.action.ShowReviewBoard$2$1.run(ShowReviewBoard.java:78)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:409)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:398)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:818)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`
Plugin Version: 0.1.3

IntelliJ IDEA 2017.1 EAP
Build #IU-171.2613.7, built on January 25, 2017
IntelliJ IDEA EAP User
Expiration date: February 24, 2017
JRE: 1.8.0_121-b13 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by anshnd** [comment]
Latest IDEA solves the issue.  I wonder why it didn't prompt me to update the plugin and I had to do it manually
