### ISSUE TITLE
exception in 0.1.4 with pycharm 2018.3.4

### ISSUE THREAD

**Issue by arthurwoo** [ritesh-kapoor/review-board-idea-plugin#60]
java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils
	at com.ritesh.idea.plugin.reviewboard.ReviewDataProvider$2.run(ReviewDataProvider.java:271)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FilenameUtils PluginClassLoader[com.ritesh.intellij.plugin.reviewboard, 0.1.4] com.intellij.ide.plugins.cl.PluginClassLoader@69d0f94b
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by ionutm21** [comment]
It throws the same exception on my end as well...
It looks like it is related to the  commons-io-x.x.jar. 
On my Mac I run pycharm on the java runtime provided by Jetbrains.
