### ISSUE TITLE
Connection to reviewboard server fails with 404 on Intellij IDEA 2020

### ISSUE THREAD

**Issue by ohle** [ritesh-kapoor/review-board-idea-plugin#63]
When configuring the server URL and clicking "Test Connection", an error dialog saying "Status: HTTP/1.1 404 Not Found" appears.

Here is the relevant stack trace from the log:
```
com.ritesh.idea.plugin.exception.UnexpectedResponseException: Status: HTTP/1.1 404 Not Found
	at com.ritesh.idea.plugin.util.HttpRequestBuilder.asJson(HttpRequestBuilder.java:163)
	at com.ritesh.idea.plugin.reviewboard.ReviewBoardClient.testConnection(ReviewBoardClient.java:251)
	at com.ritesh.idea.plugin.reviewboard.ReviewDataProvider.testConnection(ReviewDataProvider.java:160)
	at com.ritesh.idea.plugin.state.SettingsPage$2.throwableCall(SettingsPage.java:130)
	at com.ritesh.idea.plugin.state.SettingsPage$2.throwableCall(SettingsPage.java:124)
	at com.ritesh.idea.plugin.ui.TaskUtil$3.call(TaskUtil.java:70)
	at com.ritesh.idea.plugin.ui.TaskUtil$3.call(TaskUtil.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.ritesh.idea.plugin.util.HttpRequestBuilder.asJson(HttpRequestBuilder.java:161)
	... 11 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 16 more
```

Intellij 2018 seems to work.

**Comment by jennifer-richards** [comment]
Seeing this too with PyCharm Professional 2020.1
