### ISSUE TITLE
NPE with publish review when right clicked changed files

### ISSUE THREAD

**Issue by sjsun-hc** [ritesh-kapoor/review-board-idea-plugin#9]
It really great that the plugin now can support svn. Thanks a lot, guys.

Now when I righ click some changed files and select the "Publish Review", an NPE is thrown and no review could be published.
# Not sure what is wrong with, the plugin itself? or my configurations on the review board.

null
java.lang.NullPointerException
    at com.ritesh.idea.plugin.ui.action.ShowReviewBoard.actionPerformed(ShowReviewBoard.java:55)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:144)
    at com.intellij.notification.Notification.<init>(Notification.java:70)
    at com.intellij.notification.Notification.<init>(Notification.java:48)
    at com.ritesh.idea.plugin.ui.ExceptionHandler$1.run(ExceptionHandler.java:76)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ritesh-kapoor** [comment]
What is the current plugin version you are using?

**Comment by sjsun-hc** [comment]
I installed the plugin from the ideaj's plugin repository,which is of version 0.1.1, my ideaj's version 14.1.5. I also tried it with 15.0.1 Ultimate, but not luck.
...
Change Notes
Version 0.1.1
Bug fixes
Adding Subversion support
Supporting IDEA 15
....

**Comment by ritesh-kapoor** [comment]
Looking into the exception the source code it is stating is pointing to previous release. Could you please confirm if the issue persist? Attaching screenshot would be help ful

**Comment by sjsun-hc** [comment]
![plugin_version](https://cloud.githubusercontent.com/assets/14805999/11866651/62c704c2-a4e7-11e5-827c-0ea6a3d1df6e.PNG)
I cannot find the "Publish Review" menu item any more. Don't know why.

**Comment by ritesh-kapoor** [comment]
Can you find review button here.
http://plugins.jetbrains.com/files/7872/screenshot_15485.png

**Comment by sjsun-hc** [comment]
Great, I can find the review button according to your guide.
But now, after I submit the request, the ideaj told me "5:23:17 PM ReviewBoard Server: Server : The file was not found in the repository." and failed to submit.
while the file was checked out from the svn because I can diff it.
Attached is the stacktrace screenshot.
The button is now the only button for reviewboard, is it?  I actually could not find the "publish review" menu.
![cap1](https://cloud.githubusercontent.com/assets/14805999/11893462/cfec08da-a5ab-11e5-9856-edda6c0c7ffc.PNG)
![cap2](https://cloud.githubusercontent.com/assets/14805999/11893463/cfed0d16-a5ab-11e5-88e9-f4665adc6444.PNG)
![cap3](https://cloud.githubusercontent.com/assets/14805999/11893464/cfed4f74-a5ab-11e5-88d0-1db0a0115ef2.PNG)

**Comment by sjsun-hc** [comment]
It seems to me the file was not uploaded since I can find a new review request was submitted to the review board while no file was uploaded.

**Comment by ritesh-kapoor** [comment]
Closing this issue and raising 2 new issues seperately
